/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.*;







public class Ventana_definir_bloques extends javax.swing.JDialog {

    ArrayList<PredioSeleccionado> listaSelec = new ArrayList();
    ArrayList<Predio> entradaGrasp = new ArrayList();
    
    public Ventana_definir_bloques(java.awt.Frame parent, boolean modal,ArrayList<Predio> entradaG,ArrayList<PredioSeleccionado> listaS) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        for(int i=0;i<listaS.size();i++){ // se pasan datos del arraylist al arraylist global
            listaSelec.add(listaS.get(i));
        }
        
        for(int i=0;i<entradaG.size();i++){ // se pasan los datos que entraran al Grasp
            entradaGrasp.add(entradaG.get(i));
        }
        
        
        
        panel.setBackground(Color.GRAY); // se le da el color gris al panel
        String rango_inicial=calcularRangoHora(0);
        
        //se inicializa y se centraliza campo de bloque
        campo_bloque.setText("0");
        campo_bloque.setHorizontalAlignment(campo_bloque.CENTER);
        
        // se inicia y se centraliza parametro en campo de tiempo
        campo_tiempo.setText(rango_inicial);
        campo_tiempo.setHorizontalAlignment(campo_tiempo.CENTER);
        campo_tiempo.setEditable(false);
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        campo_tiempo = new javax.swing.JTextField();
        campo_bloque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_titulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 640, 110, 40));

        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMouseEntered(evt);
            }
        });

        campo_bloque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_bloqueKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_bloqueKeyTyped(evt);
            }
        });

        jLabel4.setText("Ingresar cantidad de bloques :");

        jLabel5.setText("Rango de tiempo por bloque   :");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(campo_bloque))
                .addGap(45, 45, 45))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_bloque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 390, 190));

        panel_titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresar la cantidad de bloques en las que");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("se dividira la jornada laboral");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 390, 60));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-tomates.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseEntered
        
    }//GEN-LAST:event_panelMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void campo_bloqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_bloqueKeyTyped
        //campo_tiempo.setText(campo_bloque.getText());
    }//GEN-LAST:event_campo_bloqueKeyTyped

    private void campo_bloqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_bloqueKeyReleased
        //campo_tiempo.setText(campo_bloque.getText());

        if(campo_bloque.getText().length()>0){
            int numeroBloques = Integer.parseInt(campo_bloque.getText());
            if(numeroBloques ==0){
                campo_tiempo.setText(calcularRangoHora(0)); 
            }else{
                float div = 1440/numeroBloques;
                String rangoTiempo = calcularRangoHora(div);
                campo_tiempo.setText(rangoTiempo);   
            }
        }else{
            campo_tiempo.setText(calcularRangoHora(0)); 
        }
        
        
    }//GEN-LAST:event_campo_bloqueKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(campo_bloque.getText().equals("") || campo_bloque.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad de bloques que se utilizaran", " Mensaje", JOptionPane.WARNING_MESSAGE); 
        }else{
            int bloque = Integer.parseInt(campo_bloque.getText());
           
            ventana_capacidad_descarga dialog = new ventana_capacidad_descarga(new javax.swing.JFrame(), true,entradaGrasp,listaSelec,bloque,campo_tiempo.getText());
            dialog.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public static String calcularRangoHora(float hraMin){
        int hra, min, seg;
        String horafinal;
        
        hra = (int) (hraMin/60);
        min = (int) (hraMin%60);
        seg = (int) ((hraMin%60)*60)%60;
        
        if (hra>23) {
            hra=hra-24;
        }
        
        horafinal=hra+":";
        
        if (min<10) {
            if(seg<10){
                horafinal+="0"+min+":0"+seg;
            }
            else{
                horafinal+="0"+min+":"+seg;
            }
        }
        else if(seg<10){
            horafinal+=min+":0"+seg;
        }
        else{
            horafinal+=min+":"+seg;
        }
        
        return horafinal;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_bloque;
    private javax.swing.JTextField campo_tiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_titulo;
    // End of variables declaration//GEN-END:variables
}
