/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelos.*;


import static ventanas.ventana_ejecucion_grasp.inputGrasp;
import static ventanas.ventana_capacidad_descarga.eventoBoton;
import static ventanas.ventana_ejecucion_grasp.listaSelec;
import static ventanas.ventana_ejecucion_grasp.capDescarga;

public class ventana_modificar_cargas extends javax.swing.JDialog {
    
   
    List<JTextField> campos = new ArrayList<>(); // para guardar contenido de los campos de textos
    public static int cargasTotales=0;
    public static int cantidadCargas=0;
    public ventana_modificar_cargas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        panel.setBackground(Color.GRAY);       
        GridBagLayout gridBag = new GridBagLayout (); // se selecciona tipo de layout
        panel.setLayout(gridBag);
        GridBagConstraints restricciones = new GridBagConstraints ();
        restricciones.weightx = 1.5;
        cantidadCargas=ventanas.ventana_ejecucion_grasp.inputGrasp.size();
        
        for(int i=0;i<ventanas.ventana_ejecucion_grasp.inputGrasp.size();i++){
            
            restricciones.gridwidth = GridBagConstraints.RELATIVE;
            JLabel label= new JLabel(listaSelec.get(i).getNombre_predio());
            gridBag.setConstraints (label, restricciones);      // se agrega restriccion
            panel.add(label); 
            
            restricciones.gridwidth = GridBagConstraints.REMAINDER; // campo de texto, ultimo en la fila
            JTextField input = new JTextField(10);
            input.setHorizontalAlignment(JTextField.CENTER);
            input.setText(String.valueOf(ventanas.ventana_ejecucion_grasp.inputGrasp.get(i).getNumC()));
            input.addKeyListener(new KeyAdapter(){ // se crea restriccion para evitar que se ingresen letras, 
                public void keyTyped(KeyEvent e)   // numeros flotantes, o negativos.
                {
                    char car= e.getKeyChar();
                    if((car<'0' || car>'9') && (car!=',' || car!='.' )) e.consume();
                    
        
                }
            });
            gridBag.setConstraints (input, restricciones);          // se agregan restricciones
            panel.add(input);
            campos.add(input);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        panel_titulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 110, 50));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 430, 340));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 110, 50));

        panel_titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Modificar predio por carga");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(panel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-tomates.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        cargasTotales=0;
        for(int i=0;i<ventana_ejecucion_grasp.inputGrasp.size();i++){ // se recalculan las cargas totales
            cargasTotales=cargasTotales+ventana_ejecucion_grasp.inputGrasp.get(i).getNumC();
        }
        
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       
        PredioModel pm = new PredioModel();
        ventana_ejecucion_grasp.inputGrasp.clear();
        ArrayList<Integer> cargas = new ArrayList(); // arreglo para volver a almacenar las cargas
        for(JTextField txt: campos){// se leen datos 
                
                cargas.add(Integer.parseInt(txt.getText())); // se almacenan cargas
                
        }
        for(int i=0;i<cantidadCargas;i++){
            int km_talca=pm.llamar_predio_seleccionado(ventana_ejecucion_grasp.listaSelec.get(i).getId());
            Predio pr;
            float tiempo= (float)km_talca/50*60; // se multiplican por 60 para que se midan en minutos
            float tiempoC = (float)10/cargas.get(i)*60;
            pr=new Predio(listaSelec.get(i).getLugar(),cargas.get(i),tiempoC,tiempo);
            ventana_ejecucion_grasp.inputGrasp.add(pr);
            
        }
          
        
        int capDesc=0;
        cargasTotales=0;
        for(int i=0;i<ventana_ejecucion_grasp.inputGrasp.size();i++){ // se recalculan las cargas totales
            cargasTotales=cargasTotales+ventana_ejecucion_grasp.inputGrasp.get(i).getNumC();
        }
        
        
        
        
        JOptionPane.showMessageDialog(null,"Modificacion realizada con exito");
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_modificar_cargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_modificar_cargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_modificar_cargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_modificar_cargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventana_modificar_cargas dialog = new ventana_modificar_cargas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_titulo;
    // End of variables declaration//GEN-END:variables
}
